### PR TITLE
make app.rb optional

### PR DESCRIPTION
**Pull request by ryfow**
Newly generated projects bomb out with a load error because app.rb doesn't exist. This checks for existence before requiring.

### CODE REVIEW

**Comment by mattetti** [comment]
Newly generated contain the app.rb file, how did you generate the app? I might be doing something wrong. It also doesn't bomb for me. I don't really mind putting a conditional requirement but I just want to make sure we are solving the right issue before 1.0

**Comment by ryfow** [comment]
Odd. I must have had my repository in a goofy state

**Comment by ryfow** [comment]
Ahh. I bet I was calling the binary wd_sinatra from my repository, but was using an incompatible template in my rubygems installation.  Sorry about that.

**Comment by mattetti** [comment]
Giving you commit rights nonetheless, note that you also have commit access.

**Pull request closed without merging**
