### PR TITLE
Allow documentation to be specified in the param definition

### PR DESCRIPTION
**Pull request by ryfow**
In my service params definition, I want to specify documentation like I do for responses. This patch allows for:

service.params do |p|
    p.string :email , :doc => "Email address of the recipient."
end

### CODE REVIEW

**Comment by mattetti** [comment]
This is a nice workaround, there is a TODO in Weasel-Diesel's README https://github.com/mattetti/Weasel-Diesel to add support for this more consistent doc API.
Would you mind fixing the problem in WD too please?
Also, I'm giving you commit rights on this repo, thanks for all your work and welcome to the team!

**Comment by ryfow** [comment]
Thanks.

The WD problem is just docs, right?

**Comment by mattetti** [comment]
Kinda, basically, when a service param is described as you did, the info should be available in `api.doc.params_doc[rule.name.to_sym]` in other words, the info should be available in the `params_doc` hash after the service object was initiated.

**Comment by ryfow** [comment]
Gotcha.

**Pull request merged**
