### PR TITLE
Simpler, more compact documentation template. 

### PR DESCRIPTION
**Pull request by raul**
Other than aesthetic changes, this PR removes `WD::Response::Element#to_html` and Bootstrap dependencies. I couldn't resist being too agressive and ended up mixing changes in the styles and the templates at the same time, sorry about that!

You can see a [sample generated doc](http://f.cl.ly/items/0W352Y2B1c011C0O2V2I/index.html).

### CODE REVIEW

**Comment by mattetti** [comment]
thanks, I merged in your changes. I almost want to consider building the template using jekyll or something like that so the doc gets automatically generated vi a post commit hook and the doc is available online, thoughts? /cc @kamui

**Comment by kamui** [comment]
Hmm.. somehow my comment didn't show up after I hit Comment. I'll try and remember what I wrote:

That sounds interesting, if this were to happen, I'd recommend https://github.com/middleman/middleman over jekyll, since jekyll is more blog oriented. Middleman also has extensions to deploy to github pages, S3/Cloudfiles/Cloud Storage (via fog), or just rsync. Maybe we could generate the docs in Markdown initially and pass that through middleman to generate the html, that way we can also close #12 as well.

**Comment by mattetti** [comment]
sounds good to me.

**Comment by kamui** [comment]
Working with the doc generation, I had forgotten what it looked like before this PR was merged and I just looked at https://github.com/mattetti/sinatra-web-api-example/tree/master/doc to remember. I actually much preferred the look of the original theme. I liked the color coding of the params, type, defaults, code example, etc. I think the left handed navigation works better. The way the docs looked is what partially got me excited about trying WD. I'm not sure why simplifying the look and removing Bootstrap was necessary. The end user can't modify the template, so really it's just making it harder for us to style and beautify it.

API documentation is never going to be the user's main product. It's importance is conveying the API endpoints, inputs, outputs, description, examples and hopefully being easy to navigate if your API is huge. In the documentation code's current state, we should optimize it for us to easily maintain and style. Unless we get a good designer and/or front end dev on board, why not use Bootstrap to help us get there, that's what it's for. I think we should consider using Bootstrap 3.0 in fact, it'll also get us responsive design and we could make use of Bootstrap 3.0's themes for free.

**Pull request merged**
