### PR TITLE
Switch generated sinatra app from classic to modular style

### PR DESCRIPTION
**Pull request by kamui**
I tried to `hub pull-request -b mattetti:master -i 26` for issue #26, but it said I couldn't change the issue, so I created a new PR.

I'm not sure I'm using `template` [here](https://github.com/kamui/wd-sinatra/blob/modular/bin/wd_sinatra#L49-L55) the best way, because it's copying the entire app template over, and then this method renders the rb files over the copied files. Maybe there's a better way to do that.

Also, I'm not sure what goes in `sinatra_config.rb` vs `middleware.rb`. For instance, you had `use Rack::ContentLength` defined in both places. Technically, any rack or sinatra middleware could be defined in either place.

`middleware.rb` gets loaded, then routes, then `sinatra_contrib.rb`. That means any helpers you want to define need to go into `middleware.rb` because the route service implementations might refer to helpers not defined yet right? Also, I was tempted to use `Sinatra::ConfigFile`, but that would have to be defined in `app.rb` since other libraries would need access to those config settings. I'm just a little confused with what goes where.

### CODE REVIEW

**Comment by mattetti** [comment]
@kamui I took notice of your PRs and comments, but I'm currently at Portland for RailsConf and didn't have much free time. Sorry for not responding faster. Your issues/PRs are on my TODO list.

**Comment by kamui** [comment]
No problem ;D. Take your time, hope RailsConf is a blast!

**Comment by mattetti** [comment]
Thanks, I'm not really attending RailsConf, just hanging out with co-workers and friends. From what I hear people are enjoying the conf and PDX is such a great city!

**Comment by kamui** [comment]
The generator now defines the `Requester#app` in the test helpers, so the tests pass now. I started reorganizing the test helper to include the TestApi methods instead of encapsulating everything inside of TestApi, but I realized it was a lot of code changes, so I'll put that in a separate PR.

**Comment by mattetti** [comment]
Sounds good, flying the Scotland tomorrow but I hope to be able to review
your PRs soon

**Comment by kamui** [comment]
Sounds good, have fun in Scotland. I'll wait for these 2 to get merged in before I submit more PRs. It's getting hard to juggle between multiple branches that rely on changes from other branches.

**Comment by kamui** [comment]
Looks like minitest 5.0.0 was released and it's causing failures.

**Comment by mattetti** [comment]
It looks good, I didn't try to generate an app yet and play with it but I think that if you're confident we should merge that and prepare a 2.0 release containing all the goodies you've been working on.

What do you think?

**Comment by mattetti** [comment]
One more thing, we need to make sure one can update an older version of a WD app by running the generate command as per the documentation.

**Comment by kamui** [comment]
Hmm.. what does that mean exactly?

If you rerun the generator on top of an older WD app and overwrite existing files, I think only new services written will be the only things not encapsulated by the App class. How should we deal with those?

When I have a chance, I'll try and rerun the generator on top of a non modular WD and see if there are any other issues.

**Comment by mattetti** [comment]
So the way it should work is that it should offer to replace some files and give you a diff option.
In theory most generated files can be replaced unless they were modified.
In other words, if you generate a brand new app using the old gem and then regenerate on top of it and replace everything, it should still work.

If it doesn't work because of the way apps are generated we should provide a way to "easily" upgrade existing apps.

**Comment by kamui** [comment]
I generated a 1.0.6 wd-sinatra app and then reran the generator with the modular branch overwriting the conflicts and everything worked. You do get an error because the 1.0.6 released gem doesn't have a `rack-parser` dependency, but once you release a new version that won't be an issue.

So the only issue with current WD apps, is that the services created after first generating an app will have to be manually wrapped in the app class. What's the best way to communicate this? Maybe a wiki entry about upgrading from 1.0.x to 2.x (or 1.1.x)? The upgrade should be "easy", just wrap each api service in:

``` ruby
class MyAppName < Sinatra::Base
  # describe_service ... do |service|
  #   ... code here
  # end
end
```

What do you think?

**Comment by kamui** [comment]
Hmm.. actually, the api services don't need to be wrapped with the App class at all. The service looks so much like Sinatra route code that I forget that wd-sinatra defines the route and dispatches each service handler.

So, then the only issue left is that the [load_sinatra_route](https://github.com/mattetti/wd-sinatra/blob/master/lib/wd_sinatra/sinatra_ext.rb#L123-L125) method should use the  Sinatra subclassed app class to define the routes, not `Sinatra::Base`. So... how do I access the app class from within wd-sinatra...

**Comment by kamui** [comment]
Maybe pass the app class into the AppLoader?

``` ruby
WDSinatra::AppLoader.server(root, MyApp)

# app_loader.rb
    def app
      @app
    end

    # Boot in server mode
    def server(root_path, sinatra_app)
      @app = sinatra_app
      @root = root_path
      unless @booted
        console(root_path, app)
        load_middleware
        set_sinatra_routes
        set_sinatra_settings
        load_hooks
      end
    end

    def set_sinatra_routes
      WSList.sorted_for_sinatra_load.each{|api| api.load_sinatra_route(app) }
    end

# sinatra_ext.rb
  def load_sinatra_route(sinatra_app)
    # ...
    sinatra_app.send(:route, upcase_verb, self.url) do
      env['wd.service'] = service
      service.handler.dispatch(self)
    end
  end
```

**Comment by mattetti** [comment]
Thinking out loud, so bear with me.
Looking at
https://github.com/mattetti/wd-sinatra/blob/master/lib/wd_sinatra/sinatra_ext.rb#L112
I wonder if the routes are actually loaded in the right subclass.
`describe_service` populates `WSList` which is then used to create routes.
But I'm not sure declaring the services inside a `Sinatra::Base` subclass
makes a difference. Am I wrong?

If I'm right and we need one more tweak to associate services to their
wrapping class, we probably should be able to detect the fact that we are
lacking context and create an anonymous/default subclass.

Thoughts?

**Comment by kamui** [comment]
If you define the routes in `Sinatra::Base` and you have another sinatra app mounted in config.ru, won't that app and any future apps that inherit from `Sinatra::Base`, inherit those routes as well?

I added this to config.ru in my modular sinatra app:

``` ruby
require 'rubygems'
require 'wd_sinatra/app_loader'
root = File.expand_path(File.dirname(__FILE__))
WDSinatra::AppLoader.server(root)
map("/first") { run MyApp }

class Second < Sinatra::Base
end
map("/second") { run Second }
```

`GET /first/hello_word` and `GET /second/hello_word` will both respond with json.

**Comment by mattetti** [comment]
so I like the suggestion of using:

``` ruby
def load_sinatra_route(sinatra_app=Sinatra::Base)
```

Where would we define the app's class tho? Should we do like Rails and create a custom class and let the user's overwrite it if they want to?

I also agree that it's better to not pollute the Sinatra::Base class.

**Comment by kamui** [comment]
That looks good to me, so if you don't pass in the App class it'll define it like a classic Sinatra app.

Well, in my example, I passed the app class into the AppLoader. I was thinking of just using Thor templates and pass the App class as a parameter into the #server and #console calls. So when you generate the app, it'll just put the App class there. What do you think?

**Comment by mattetti** [comment]
Sounds good to me

**Comment by kamui** [comment]
I don't know why this didn't occur to me, but the app class isn't defined until the `AppLoader` executes `#load_middleware`, so you can't pass in an undefined class as a method arg to `#server`. Argh!

**Comment by mattetti** [comment]
I can think of a quick solution, declare the app class in the rackup file: https://github.com/mattetti/wd-sinatra/blob/master/templates/config.ru#L4 and pass it as a second argument

The apploader could be a bit clever and handle 3 cases:
- a class being passed
- nil being passed (create a class on the fly)
- a symbol/string, create a class matching the name.

It sounds a bit dirty, but not too complicated at the same time. What do you think?

**Comment by kamui** [comment]
I was actually thinking of the 3rd thing you posted, but I thought it sounded too dirty, pass a string and `#cameize`/`#constantize` it. Maybe as a temporary solution until we can think of a better one?

I thought of declaring the app class in config.ru too, but `#server` is called in Rakefile, doc.rake, and test_helpers.rb too. It would be messy to predefine it in all 4 places. Then I thought about defining it in `lib/app.rb` and then app loading could be a 2 step process, `#load_app_file`, then `#server`, but that sounds dirty too.

Why would you need to handle nil? How would you rack mount it if it was created on the fly? I guess the AppLoader could return the generated class, but what's the use case for that situation?

Going to experiment a little with it.

**Comment by kamui** [comment]
I implemented passing in nil (defaults to `Sinatra::Base`), symbol or string into `#server`. The Thor templates use a string version of the const. Tests pass, generated app tests pass, rake tasks work, rackup responds to requests.

Let me know what you think.

**Comment by kamui** [comment]
After looking at it for a bit, I think maybe a 2 step boot process might be better. This string/symbol conversion to a class just feels nasty. How about something this:

``` ruby
    def server(sinatra_app=nil)
      raise StandardError, "Must run WDSinatra::AppLoader#setup first." unless root_path
      unless @server_loaded
        load_middleware
        sinatra_app ? set_sinatra_routes(sinatra_app) : set_sinatra_routes
        set_sinatra_settings
        load_hooks
        @server_loaded = true
      end
    end

    def setup(root_path)
      @root = root_path
      unless @booted
        set_env
        set_loadpath(root_path)
        load_environment
        load_lib_dependencies
        load_app_file
        load_models
        load_apis
        @booted =  true
      end
```

And then you can start the server like:

``` ruby
root = File.expand_path(File.dirname(__FILE__))
WDSinatra::AppLoader.setup(root)
WDSinatra::AppLoader.server(App)
```

And console could just use setup:

``` ruby
# bin/console
root = File.expand_path(File.dirname(__FILE__))
WDSinatra::AppLoader.setup(root)
```

**Comment by mattetti** [comment]
I don't understand this line of code:

``` ruby
sinatra_app ? set_sinatra_routes(sinatra_app) : set_sinatra_routes
```

(also, maybe the sinatra settings should be set before the routes (?))

Overall, I like the separated steps, it makes things much cleaner and it keeps the console/jobs pretty clean.

**Comment by kamui** [comment]
Moving the settings to before routes makes sense. I'll do that.

Re: that line, it just says if sinatra_app is nil, then don't pass it as an argument to `#set_sinatra_routes`.

``` ruby
    def set_sinatra_routes(sinatra_app=Sinatra::Base)
      # ...
    end
```

The method signature looks like this. I could default sinatra_app to `Sinatra::Base` in `#server`, but we're passing `sinatra_app` from `#server` to `#set_sinatra_routes`, to `#load_sinatra_route`, I figure I'd default to nil, and if the user doesn't define it then it'll call `#set_sinatra_routes` without the `sinatra_app` param.

**Comment by mattetti** [comment]
I think I would prefer it like that:

``` ruby
def server(sinatra_app=nil)
      raise StandardError, "Must run WDSinatra::AppLoader#setup first." unless root_path
      unless @server_loaded
        load_middleware
        set_sinatra_settings
        set_sinatra_routes(sinatra_app)
        load_hooks
        @server_loaded = true
      end
    end
```

``` ruby
def set_sinatra_routes(sinatra_app=nil)
  sinatra_app ||= Sinatra::Base
   # ...
end
```

What do you think?

**Comment by kamui** [comment]
Looks good to me, should we do the same thing in `#load_sinatra_route` in sinatra_ext.rb?

**Comment by mattetti** [comment]
good idea, let's keep the code consistent.

**Comment by kamui** [comment]
I rebased this, but lost my comment in the push. In the last commit, I merged loading middleware and sinatra_config. In a modular app, middleware will be defined inside the app class anyhow and we moved sinatra_config to load before the api routes, so unless I'm missing something, middleware should just be defined in sinatra_config.

**Comment by kamui** [comment]
@mattetti I'm going to be leaving for Japan for a month (vacation, woohoo!) on June 1st. If possible, I'd like to get this ticket merged before then so let me know if there are any remaining issues with it. Thanks!

**Comment by mattetti** [comment]
Sorry I missed your previous comment, I think we are good, I'll merge it now and we can test it from master and revert in case of major problems.

Enjoy your vacation!

**Pull request merged**
