### PR TITLE
Switch to Rack::Parser

### PR DESCRIPTION
**Pull request by kamui**
I'm just curious why you implemented your own body parser instead of using [Rack:: PostBodyContentTypeParser](https://github.com/rack/rack-contrib/blob/master/lib/rack/contrib/post_body_content_type_parser.rb). The biggest difference I guess is being able to pass in your own json parser.

Edit: [Rack::Parser](https://github.com/achiu/rack-parser) uses MultiJSON and MultiXML and allows you to use any custom parser.

### CODE REVIEW

**Comment by kamui** [comment]
`rack-parser` uses MultiXML and MultiJSON and allows custom parsers, so I swapped your `BodyParser` for it. Works on my local app.

**Comment by mattetti** [comment]
Seems good, my only worry was to lose the useful `params_preprocessor_hook`. But after looking more in depth, the hook will still work since it's defined there: https://github.com/mattetti/wd-sinatra/blob/master/lib/wd_sinatra/sinatra_ext.rb#L73  

At this point it looks like the only induced change is that we are parsing the params earlier in the request life cycle.
It also offers more flexibility regarding param parsing by relying on rack-parser.

Thank you very much @kamui

**Pull request merged**
